on: pull_request
name: CI
jobs:
  job1:
    runs-on: machine1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.4
        with:
          since_last_remote_commit: 'true'
      - name: get_modified_files
        id: diff
        working-directory: './diff_files'
        run: |
          git config diff.renameLimit 99000
          git fetch origin $GITHUB_BASE_REF --depth=1
          touch files.txt
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file >> files.txt
          done
          cat files.txt | split -l 100 -a 8
          rm files.txt
          export filename_string=""
          for i in `ls`; do export filename_string=$filename_string"file!"$i; done
          echo "::set-output name=filenames::$filename_string"
