on: pull_request

name: "Coding Standard"
description: "A Github Action that runs the Magento Coding Standard."

secrets:
  GH_BOT_TOKEN: "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"

jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Run PHPCS inspection
      uses: rtCamp/action-phpcs-code-review@v2
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        SKIP_FOLDERS: "tests,.github"
        PHPCS_SNIFFS_EXCLUDE: "WordPress.Files.FileName"
      with:
        args: "PHPCompatibility"
