on: pull_request

name: Inspections
secrets:
  GH_BOT_TOKEN:
     required: true
     default: "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"
     description: "PHP version used to do the coding standard check."
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Run PHPCS inspection
      uses: rtCamp/action-phpcs-code-review@v2
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        SKIP_FOLDERS: "tests,.github"
        PHPCS_SNIFFS_EXCLUDE: "WordPress.Files.FileName"
      with:
        args: "PHPCompatibility"
