on: pull_request
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
          PATTERNS: '*.php'
          RELATIVE: 'app/code'
      - run: |
          git diff ${{github.event.before}} ${{github.sha}}
